### ISSUE TITLE
how to pass the sha as input to GHA 

### ISSUE THREAD

**Issue by omkarkhatavkar** [WyriHaximus/github-action-wait-for-status#129]
@WyriHaximus I have a case where I wanted to auto-merge the cherry-picks PRs. Because it is a cherry-pick PR with the latest code I'm getting the old/parent PRs sha. Can the correct sha be passed as input to GitHub action?

**Comment by WyriHaximus** [comment]
We're passing in a list of sha's during boot anyway. So replacing those with the sha from an input should not have a big code impact.

**Comment by omkarkhatavkar** [comment]
is that something where code changes need to be done from your side or basically I can still pass the sha as input from the gha yaml

**Comment by WyriHaximus** [comment]
@omkarkhatavkar Try it outL

```yaml
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@add-the-ability-to-overwrite-the-automated-sha-detection"
        with:
          commitSha: COMMIT_SHA_YOU_WANTO_TO_WAIT_FOR_HERE
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
