### ISSUE TITLE
wait-for-status triggered on pull_request fails to detect failed jobs

### ISSUE THREAD

**Issue by Crow-EH** [WyriHaximus/github-action-wait-for-status#21]
**[UPDATE]:** Since 5786ef2, wait-for-status triggered on pull_request does not detect failed jobs. See  https://github.com/WyriHaximus/github-action-wait-for-status/issues/21#issuecomment-670522475

Hi !

Since we upgraded from `d2ddfe5` to `v1` all our check jobs finish in success with a weird message (since other jobs are already in progress) : `No statuses found, assuming success`.

I would have linked one of our jobs here, but since it also happens in the CI here, juste see your CI logs :smile: :
https://github.com/WyriHaximus/github-action-wait-for-status/runs/907377690?check_suite_focus=true

It seems pretty weird to me. Is it intended ?

PS: Still love your action anyway :heart:

**Comment by WyriHaximus** [comment]
Look at https://github.com/ekino/docker-buildbox/pull/313 you are only using Github Actions correct? So within the Github API there are two kinds of commit "statuses" the older `statuses` and the newer `checks`. Generally, that message means it couldn't find any `statuses` and just assumes those are fine, but it doesn't ignore any `checks`. I'll see how I can improve this 👍 , thank you for reporting

**Comment by Crow-EH** [comment]
Ok I get the distinction.

We still have a problem anyway : It also pass even when GitHub Actions checks fail.

See this check suite for example : https://github.com/ekino/docker-buildbox/pull/316/checks?check_run_id=948414227

(taking a screenshot for posterity)

Here we have `check` in success, when it should have failed because of the `php` jobs 
![image](https://user-images.githubusercontent.com/3366767/89514214-db91e900-d7d5-11ea-816b-6eff4bc3ccdd.png)

It used to work (fail successfully) before upgrading.

Here is our check action for reference :
```
name: Build Checker

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for commit statuses
        id: status
        uses: WyriHaximus/github-action-wait-for-status@v1
        with:
          ignoreActions: check
          checkInterval: 60
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Succeed
        if: steps.status.outputs.status == 'success'
        run: exit 0
      - name: Fail
        if: steps.status.outputs.status == 'failure'
        run: exit 1
```
