### ISSUE TITLE
Cancelled workflow reported as error

### ISSUE THREAD

**Issue by tbekaert** [WyriHaximus/github-action-wait-for-status#48]
Hi !

I use this action to trigger a slack notification once every job has finished in a PR workflow.

My problem is I use [n1hility/cancel-previous-runs](https://github.com/n1hility/cancel-previous-runs) to cancel previous run attached to that PR and wait-for-status report those cancelled jobs as errors.

Can it be possible to report them as cancellation?

Here is the slack job I use, for reference:
```yml
slack:
    name: Send slack notification
    runs-on: ubuntu-latest
    if: always()
    needs: [standard,jest]
    steps:
      - name: Wait for status checks
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          checkInterval: 10
          ignoreActions: Send slack notification
      - name: Send PR slack notification
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          status: ${{ steps.waitforstatuschecks.outputs.status }}
          success_text: 'Tests on PR "${{github.event.pull_request.title}}" (<${{github.event.pull_request._links.html.href}}|${{github.head_ref}}>) completed successfully'
          failure_text: 'Tests on PR "${{github.event.pull_request.title}}" (<${{github.event.pull_request._links.html.href}}|${{github.head_ref}}>) failed'
          cancelled_text: 'Tests on PR "${{github.event.pull_request.title}}" (<${{github.event.pull_request._links.html.href}}|${{github.head_ref}}>) was cancelled'
```

Thanks :)
